name: ACAS Version Bumper

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ACASBaseUpdate:
    name: ACAS base version check and bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest ACAS release
        id: acas-release
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/mcneilco/acas/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(<acas-release.version)
      - name: Commit base update
        if: steps.acas-release.outputs.current_tag != steps.acas-release.outputs.release_tag
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'noreply@github.com'
          branch=acas-bump-${{ steps.acas-release.outputs.release_tag }}
          git checkout -b $branch
          echo ${{ steps.acas-release.outputs.release_tag }} > acas-release.version
          git add acas-release.version
          git commit -m "Update acas-release to ${{ steps.acas-release.outputs.release_tag }}"
          git push --set-upstream origin $branch
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Update ACAS to ${{ steps.acas-release.outputs.release_tag }}',
              owner,
              repo,
              head: 'acas-release-updates',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
