name: Docker Image CI

on:
  push:
    branches: ["**"]
  create:
    tags: "**"

jobs:
  DocckerImageCI:
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
      - name: Get ACAS Tag
        run: |
          name=$(<acas-release.version)
          echo ::set-output name=current_tag::$name
          echo "ACAS Tag $name"
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

